# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 570)
        MainWindow.setMinimumSize(QtCore.QSize(800, 570))
        MainWindow.setMaximumSize(QtCore.QSize(800, 570))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 781, 531))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.title = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gotham Bold")
        font.setPointSize(28)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_5.addWidget(self.title)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.code = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        self.code.setFont(font)
        self.code.setAlignment(QtCore.Qt.AlignCenter)
        self.code.setObjectName("code")
        self.verticalLayout_5.addWidget(self.code)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.num_of_codes = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.num_of_codes.setObjectName("num_of_codes")
        self.horizontalLayout_2.addWidget(self.num_of_codes)
        self.num_codes = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.num_codes.setMinimum(1)
        self.num_codes.setMaximum(10)
        self.num_codes.setOrientation(QtCore.Qt.Horizontal)
        self.num_codes.setObjectName("num_codes")
        self.horizontalLayout_2.addWidget(self.num_codes)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.inputPC = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.inputPC.setFont(font)
        self.inputPC.setObjectName("inputPC")
        self.horizontalLayout_5.addWidget(self.inputPC)
        self.buttonPC = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        self.buttonPC.setFont(font)
        self.buttonPC.setObjectName("buttonPC")
        self.horizontalLayout_5.addWidget(self.buttonPC)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.button1 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button1.sizePolicy().hasHeightForWidth())
        self.button1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        self.button1.setFont(font)
        self.button1.setObjectName("button1")
        self.horizontalLayout_5.addWidget(self.button1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.inputPS4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.inputPS4.setFont(font)
        self.inputPS4.setObjectName("inputPS4")
        self.horizontalLayout_4.addWidget(self.inputPS4)
        self.buttonPS4 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        self.buttonPS4.setFont(font)
        self.buttonPS4.setObjectName("buttonPS4")
        self.horizontalLayout_4.addWidget(self.buttonPS4)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_4.addWidget(self.line_3)
        self.button2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button2.sizePolicy().hasHeightForWidth())
        self.button2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        self.button2.setFont(font)
        self.button2.setObjectName("button2")
        self.horizontalLayout_4.addWidget(self.button2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputXB1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.inputXB1.setFont(font)
        self.inputXB1.setObjectName("inputXB1")
        self.horizontalLayout.addWidget(self.inputXB1)
        self.buttonXB1 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        self.buttonXB1.setFont(font)
        self.buttonXB1.setObjectName("buttonXB1")
        self.horizontalLayout.addWidget(self.buttonXB1)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.button3 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button3.sizePolicy().hasHeightForWidth())
        self.button3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        self.button3.setFont(font)
        self.button3.setObjectName("button3")
        self.horizontalLayout.addWidget(self.button3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.post_pc = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(9)
        self.post_pc.setFont(font)
        self.post_pc.setObjectName("post_pc")
        self.verticalLayout_2.addWidget(self.post_pc)
        self.post_ps4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(9)
        self.post_ps4.setFont(font)
        self.post_ps4.setObjectName("post_ps4")
        self.verticalLayout_2.addWidget(self.post_ps4)
        self.post_xb1 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(9)
        self.post_xb1.setFont(font)
        self.post_xb1.setChecked(False)
        self.post_xb1.setObjectName("post_xb1")
        self.verticalLayout_2.addWidget(self.post_xb1)
        self.twitter_post = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(11)
        self.twitter_post.setFont(font)
        self.twitter_post.setObjectName("twitter_post")
        self.verticalLayout_2.addWidget(self.twitter_post)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_7.addWidget(self.line_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.status = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setObjectName("status")
        self.horizontalLayout_3.addWidget(self.status)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuTDefton_s_GCG = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.menuTDefton_s_GCG.setFont(font)
        self.menuTDefton_s_GCG.setObjectName("menuTDefton_s_GCG")
        self.menuConnections = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.menuConnections.setFont(font)
        self.menuConnections.setObjectName("menuConnections")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTwitch = QtWidgets.QAction(MainWindow)
        self.actionTwitch.setObjectName("actionTwitch")
        self.actionTwitter = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.actionTwitter.setFont(font)
        self.actionTwitter.setObjectName("actionTwitter")
        self.actionDiscord = QtWidgets.QAction(MainWindow)
        self.actionDiscord.setObjectName("actionDiscord")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.actionDocumentation.setFont(font)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionReset = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(8)
        self.actionReset.setFont(font)
        self.actionReset.setObjectName("actionReset")
        self.menuConnections.addAction(self.actionTwitter)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionReset)
        self.menubar.addAction(self.menuTDefton_s_GCG.menuAction())
        self.menubar.addAction(self.menuConnections.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GCG"))
        self.title.setText(_translate("MainWindow", "TDEFTON\'S GLYPH CODE GRABBER"))
        self.label_5.setText(_translate("MainWindow", "MOST RECENT GRAB"))
        self.code.setText(_translate("MainWindow", "-"))
        self.label_7.setText(_translate("MainWindow", "NUMBER OF CODES"))
        self.num_of_codes.setText(_translate("MainWindow", "1"))
        self.label.setText(_translate("MainWindow", "PC"))
        self.buttonPC.setText(_translate("MainWindow", "PC Location"))
        self.button1.setText(_translate("MainWindow", "GRAB PC"))
        self.label_2.setText(_translate("MainWindow", "PS4"))
        self.buttonPS4.setText(_translate("MainWindow", "PS4 Location"))
        self.button2.setText(_translate("MainWindow", "GRAB PS4"))
        self.label_3.setText(_translate("MainWindow", "XB1"))
        self.buttonXB1.setText(_translate("MainWindow", "XB1 Location"))
        self.button3.setText(_translate("MainWindow", "GRAB XB1"))
        self.label_4.setText(_translate("MainWindow", "TWITTER POST"))
        self.post_pc.setText(_translate("MainWindow", "Post PC Codes"))
        self.post_ps4.setText(_translate("MainWindow", "Post PS4 Codes"))
        self.post_xb1.setText(_translate("MainWindow", "Post XBOX ONE Codes"))
        self.twitter_post.setText(_translate("MainWindow", "Post Codes to Twitter"))
        self.label_8.setText(_translate("MainWindow", "Status: "))
        self.status.setText(_translate("MainWindow", "-"))
        self.menuTDefton_s_GCG.setTitle(_translate("MainWindow", "TDefton\'s GCG"))
        self.menuConnections.setTitle(_translate("MainWindow", "Connections"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionTwitch.setText(_translate("MainWindow", "Twitch"))
        self.actionTwitter.setText(_translate("MainWindow", "Twitter"))
        self.actionDiscord.setText(_translate("MainWindow", "Discord"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionReset.setText(_translate("MainWindow", "Reset (May Fix Bugs)"))
        self.actionReset.setToolTip(_translate("MainWindow", "(May Fix Bugs)"))

